services:
  garage:
    image: dxflrs/garage:v0.9.0
    container_name: garage_server
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3903:3903"
    volumes:
      - ./Configurations/garage.toml:/etc/garage.toml
      - garage_data:/var/lib/garage/data
      - garage_meta:/var/lib/garage/meta
    command: /garage server
    restart: always

volumes:
  garage_data:
  garage_meta: